#!/bin/sh

set -e

if [ ! -e debian/changelog ]; then
	echo "error: no debian/changelog" >&2
	exit 1
fi

if [ ! -e debian/control ]; then
	echo "error: no debian/control" >&2
	exit 1
fi

VERSION=$(sed -e 's/[^(]*(\([^)]*\)).*/\1/; q' < debian/changelog)

PACKAGE=$(sed -ne 's/^Package: *\(.*\) */\1/; T; p;' < debian/control)

A=$(mktemp)
B=$(mktemp)

for i in $PACKAGE; do
	dpkg -c ../${i}_${VERSION}_*.deb
done | sed -e 's/ -> .*//; s/.* //; s/\.gz$//; /\/$/d;' | sort > $A

(cd debian/tmp; find -type f -o -type l;) | sort > $B

MISSING=$(diff -u $A $B | sed -ne 's/^+\.//; T; p;')
if [ -n "$MISSING" ]; then
	echo "Unpackaged files:"
	echo $MISSING
fi

rm -f $A $B

